function scrollEvent(){is_touch_device()||(viewportTop=jQuery(window).scrollTop(),jQuery(window).width()&&jQuery(".parallax-overlay").each(function(){elementOffset=jQuery(this).offset().top,distance=.35*-(elementOffset-viewportTop),jQuery(this).css("transform","translate3d(0, "+distance+"px,0)")}))}function is_touch_device(){return"ontouchstart"in window||"onmsgesturechange"in window}!function(e){"use strict"
e.belowthefold=function(t,o){var n=e(window).height()+e(window).scrollTop()
return n<=e(t).offset().top-o.threshold},e.abovethetop=function(t,o){var n=e(window).scrollTop()
return n>=e(t).offset().top+e(t).height()-o.threshold},e.rightofscreen=function(t,o){var n=e(window).width()+e(window).scrollLeft()
return n<=e(t).offset().left-o.threshold},e.leftofscreen=function(t,o){var n=e(window).scrollLeft()
return n>=e(t).offset().left+e(t).width()-o.threshold},e.inviewport=function(t,o){return!(e.rightofscreen(t,o)||e.leftofscreen(t,o)||e.belowthefold(t,o)||e.abovethetop(t,o))},e.extend(e.expr[":"],{"below-the-fold":function(t,o,n){return e.belowthefold(t,{threshold:0})},"above-the-top":function(t,o,n){return e.abovethetop(t,{threshold:0})},"left-of-screen":function(t,o,n){return e.leftofscreen(t,{threshold:0})},"right-of-screen":function(t,o,n){return e.rightofscreen(t,{threshold:0})},"in-viewport":function(t,o,n){return e.inviewport(t,{threshold:0})}}),e(window).load(function(){if(e("#preloader").length>0&&e("#preloader").fadeOut("slow",function(){e(this).remove()}),e("#portfolio-items").length>0){var t=document.querySelector("#portfolio-items")
new Masonry(t,{itemSelector:".portfolio-item",columnWidth:".portfolio-sizer",percentPosition:!0})}if(e(".portfolio-sidebar.sidebar-list").length>0){var o=e(".portfolio-sidebar.sidebar-list"),n=e(window),i=e(".portfolio-gallery-list").height(),s=o.offset()
o.css("width",o.width()),n.scroll(function(){n.scrollTop()>s.top-120?(o.stop().addClass("fixed-sidebar"),n.scrollTop()>s.top+i-o.height()-100?o.addClass("absolute-sidebar"):o.removeClass("absolute-sidebar")):o.stop().removeClass("fixed-sidebar")})}}),e(document).ready(function(){function t(){requestAnimationFrame(t),scrollEvent()}if(e("#single-page").length>0&&e("body").addClass("single-post"),e("#customizer .switcher").click(function(){e("#customizer").toggleClass("active")}),t(),e("#footer.fixed").length){var o=e("#footer.fixed").height()
e("#wrapper").css("margin-bottom",o)}e("#s").each(function(t,o){var n=e(o).attr("id"),i=null
n&&1==(i=e(o).parents("form").find("label[for="+n+"]")).length&&(e(o).attr("placeholder","Search"),e(i).remove())}),e(".searchform input[type='submit']").val(""),e(".woocommerce-product-search input[type='submit']").val(""),e(document).on("click",".section .wpcf7-not-valid-tip,.section .wpcf7-mail-sent-ok, .subscribe-form header .wpcf7-response-output, .modal-content-inner .wpcf7-not-valid-tip",function(){e(this).fadeOut()}),e(".wpcf7-recaptcha").length>0&&e(document).on("click",".modal-menu-item",function(){grecaptcha.reset()}),e(".navbar-nav > li.one-page-link > a:first-child, .footer_widget .menu li.one-page-link > a:first-child").each(function(){var t=e(this).attr("href"),o=t.replace(/\/$/,"")
if(e("body").hasClass("home")){var n=o.substr(o.lastIndexOf("/")+1)
n.indexOf("?page_id")>=0&&(n=""),e(this).attr("href","#"+n)}else if(!e(this).hasClass("first")){var i=o.lastIndexOf("/")
o=o.substring(0,i)+"#"+o.substring(i+1),e(this).attr("href",o)}}),e("<span class='mobile-dropdown'></span>").appendTo(e(".navbar-nav .menu-item-has-children")),e(".navbar-nav .menu-item-has-children .mobile-dropdown").click(function(){e(this).closest(".menu-item-has-children").toggleClass("mobile-visible")}),e(".navbar-collapse ul li a, .navbar-collapse .modal-menu-item.scroll-section").click(function(){e(".navbar-toggle:visible").click()}),e(function(){e(".navbar-nav .one-page-link a, .footer_widget .menu li a, .scroll-section, .demo-button").bind("click",function(t){if(e("body").hasClass("home")){var o=e(this)
e("html, body").stop().animate({scrollTop:e(o.attr("href")).offset().top-68},1500,"easeInOutExpo"),t.preventDefault()}})}),e(function(){e(".portfolio-demo-button, .kd-calltoaction.smooth-scroll .tt_button").bind("click",function(t){var o=e(this)
e("html, body").stop().animate({scrollTop:e(o.attr("href")).offset().top-250},1500,"easeInOutExpo"),t.preventDefault()})}),e("body").scrollspy({offset:69,target:".navbar-fixed-top"}),e(".header-search-bar .toggle-search").click(function(){e(".header-search-bar .header-search-container").toggleClass("active"),e(this).toggleClass("fa-times")}),e(".wpglobus-selector-link").length>0&&e(".wpglobus-selector-link .dropdown-menu").addClass("sub-menu"),e(".slider-scroll-down a").click(function(t){e("html, body").animate({scrollTop:e("#wrapper .section").offset().top-68},1500,"easeInOutExpo"),t.preventDefault()}),e(window).bind("scroll",function(){e(window).scrollTop()>e(window).height()&&e(".back-to-top").addClass("active"),e(window).scrollTop()<e(window).height()&&e(".back-to-top").removeClass("active")}),e(".back-to-top").click(function(t){return t.preventDefault(),e("html, body").animate({scrollTop:0},1e3),!1})}),e(".owlslider-portfolio").length&&e(".owlslider-portfolio").owlCarousel({navigation:!1,pagination:!0,singleItem:!0,autoPlay:!1,animateOut:"fadeOut"})
var t=window.PhotoSwipe,o=window.PhotoSwipeUI_Default
e("body").on("click","a[data-size]",function(e){t&&o&&(e.preventDefault(),i(this))})
var n=function(t,o){var n,i=e(t).find("a[data-size]").has("img"),s=[]
return i.each(function(t){var i,r=e(this),a=r.data("size").split("x")
i=r.next().is(".wp-caption-text")?r.next().text():r.parent().next().is(".wp-caption-text")?r.parent().next().text():r.attr("title"),s.push({src:r.attr("href"),w:parseInt(a[0],10),h:parseInt(a[1],10),title:i,msrc:r.find("img").attr("src"),el:r}),o===r.get(0)&&(n=t)}),[s,parseInt(n,10)]},i=function(i,s){var r,a,l,c,f=e(".pswp").get(0),d=e(i).parents(".gallery, .hentry, .main, body").first()
l=n(d,i),c=l[1],l=l[0],a={index:c,getThumbBoundsFn:function(e){var t=l[e].el.find("img"),o=t.offset()
return{x:o.left,y:o.top,w:t.width()}},showHideOpacity:!0,history:!1},s&&(a.showAnimationDuration=0),r=new t(f,o,l,a),r.init()}
!function(e){function t(e){return RegExp("(^|\\s+)"+e+"(\\s+|$)")}function o(e,t){var o=n(e,t)?s:i
o(e,t)}var n,i,s
"classList"in document.documentElement?(n=function(e,t){return e.classList.contains(t)},i=function(e,t){e.classList.add(t)},s=function(e,t){e.classList.remove(t)}):(n=function(e,o){return t(o).test(e.className)},i=function(e,t){n(e,t)||(e.className=e.className+" "+t)},s=function(e,o){e.className=e.className.replace(t(o)," ")})
var r={hasClass:n,addClass:i,removeClass:s,toggleClass:o,has:n,add:i,remove:s,toggle:o}
"function"==typeof define&&define.amd?define(r):e.classie=r}(window);(function(){function e(){window.addEventListener("scroll",function(e){s||(s=!0,setTimeout(t,100))},!1),window.addEventListener("load",function(e){s||(s=!0,setTimeout(t,100))},!1)}function t(){var e=o()
e>=r?classie.add(i,"navbar-shrink"):classie.remove(i,"navbar-shrink"),s=!1}function o(){return window.pageYOffset||n.scrollTop}var n=document.documentElement,i=document.querySelector(".navbar-default"),s=!1,r=50
e()})()}(jQuery)
